# ======================================== #
# SCRIPT VARIABLES - SYSTEM
REPO_DIR="${HOME}/git_repository"
CUDA_VER="13.0"         # Latest stable version 17/08/2026
DEVICE_ENV="LINUX"      # Ubuntu

PKGS_LST=(
    build-essential
    wget
    curl
    ca-certificates
    gnupg
    pciutils
)

# ======================================== #
# SCRIPT VARIABLES - DOCKER
DOCKER_NETWORK_NAME="docker-dev-network"
DOCKER_SUBNET_IP="172.20.0.0/16"
DOCKER_GATEWAY_IP="172.20.0.1"
# ======================================== #